### PR TITLE
Install script for automatic windows installation

### PR DESCRIPTION
**Pull request by woj1993**

### CODE REVIEW

**Comment by woj1993** [comment]
Can you correct this line:
* Info above commands will remove .venv folder from directory. It is expected that it will be a folder with virtual python env.
to
* Info commands bellow will remove .venv folder from directory. It is expected that it will be a folder with virtual python env.

**Comment by woj1993** [comment]
Wait I forgot to upload my update to 2 files.

**Comment by woj1993** [comment]
Ok now it is ready.

**Comment by woj1993** [comment]
You need to resolve version changes that you comited while I was working on this. If you won't do it today I will fix this after waking up.

**Comment by ABaumher** [comment]
There are a few things i want to clean up before i merge it into main. I'll merge it into a branch and then back into main after i do that.
I'm going to add a bash version of this for MacOS users. I'm also going to move the pip installs necessary to install the plugin into their own file, like `app.txt`. Probably call it `install.txt`. If i don't, it'll install it in the plugin and that's not needed.

**Pull request merged**
