### PR TITLE
completely rewrite GameCache

### PR DESCRIPTION
**Pull request by don-de-marco**

### CODE REVIEW

**Comment by don-de-marco** [comment]
@Autistic-unicorn may I once more call you in as tester because of your massive steam library? just let it run and let me know if it breaks and how the performance feels

**Comment by Autistic-Unicorn** [comment]
Unfortunately I can't test it right now. I'm gonna get into it as soon as I'm gonna have time tomorrow :)

**Comment by engiefox** [comment]
I tried and it crashed while trying to import games from the old cache
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log](https://github.com/ABaumher/galaxy-integration-steam/files/11782855/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)
[GalaxyClient.log](https://github.com/ABaumher/galaxy-integration-steam/files/11782856/GalaxyClient.log)

**Comment by don-de-marco** [comment]
@Autistic-Unicorn no worries, I'm off to bed already and won't be able to respond within a timely manner anyway^^

@engiefox can you post the log containing the exception (preferably including the backtrace)? I'm on my phone atm and cannot open the log files there

**Comment by engiefox** [comment]
> 2023-06-18 16:38:29,536 - steam_network.websocket_client - ERROR - Failed to establish authenticated WebSocket connection AttributeError("'SteamLicense' object has no attribute 'packagie_id'")
2023-06-18 16:38:29,538 - steam_network.websocket_client - ERROR - Traceback (most recent call last):
  File "C:\Users\obliv\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\steam_network\websocket_client.py", line 111, in run
    await run_task
  File "C:\Users\obliv\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\steam_network\protocol_client.py", line 113, in run
    await self._protobuf_client.run()
  File "C:\Users\obliv\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\steam_network\protocol\protobuf_client.py", line 178, in run
    await self._process_packet(packet)
  File "C:\Users\obliv\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\steam_network\protocol\protobuf_client.py", line 518, in _process_packet
    await self._process_message(emsg, header, packet[8 + header_len:])
  File "C:\Users\obliv\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\steam_network\protocol\protobuf_client.py", line 525, in _process_message
    await self._process_multi(body)
  File "C:\Users\obliv\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\steam_network\protocol\protobuf_client.py", line 565, in _process_multi
    await self._process_packet(data[offset + size_bytes:offset + size_bytes + size])
  File "C:\Users\obliv\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\steam_network\protocol\protobuf_client.py", line 518, in _process_packet
    await self._process_message(emsg, header, packet[8 + header_len:])
  File "C:\Users\obliv\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\steam_network\protocol\protobuf_client.py", line 535, in _process_message
    await self._process_license_list(body)
  File "C:\Users\obliv\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\steam_network\protocol\protobuf_client.py", line 672, in _process_license_list
    await self.license_import_handler(licensed_apps)
  File "C:\Users\obliv\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\steam_network\protocol_client.py", line 368, in _license_import_handler
    await self._protobuf_client.get_packages_info(packages_to_import)
  File "C:\Users\obliv\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\steam_network\protocol\protobuf_client.py", line 440, in get_packages_info
    await self._send(EMsg.ClientPICSProductInfoRequest, message)
  File "C:\Users\obliv\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\steam_network\protocol\protobuf_client.py", line 482, in _send
    body = bytes(message)
  File "C:\Users\obliv\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\betterproto\__init__.py", line 629, in __bytes__
    wraps=meta.wraps or "",
  File "C:\Users\obliv\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\betterproto\__init__.py", line 360, in _serialize_single
    value = _preprocess_single(proto_type, wraps, value)
  File "C:\Users\obliv\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\betterproto\__init__.py", line 346, in _preprocess_single
    return bytes(value)
  File "C:\Users\obliv\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\steam_network\protocol\protobuf_client.py", line 438, in <lambda>
    message.packages = map(lambda x: CMsgClientPICSProductInfoRequestPackageInfo(x.packagie_id, x.access_token), steam_licenses)
AttributeError: 'SteamLicense' object has no attribute 'packagie_id'

**Comment by engiefox** [comment]
I believe that's what you want, the steam log cuts off at the bottom, let me know if you need something else. There's also these lines in the client log:
`2023-06-18 16:38:45.200 [Warning][SubSystem installer thread (4)] [TID 20888][galaxy_client]: Failed to retrieve product auth info for '1207659142' while checking for updates.
2023-06-18 16:38:45.505 [Information][SubSystem installer thread (4)] [TID 20888][galaxy_client]: Setting product event RecentlyChecked for product '1207662473' for 00min.
2023-06-18 16:38:45.811 [Information][SubSystem installer thread (4)] [TID 20888][galaxy_client]: Retrieved valid product authorisation for '1207662473' from the database.
2023-06-18 16:38:45.811 [Information][SubSystem installer thread (4)] [TID 20888][galaxy_client]: Fetching product configuration for '1207662473'.
2023-06-18 16:38:46.114 [Information][SubSystem installer thread (4)] [TID 20888][galaxy_client]: Serializing product configuration (cloud saves configuration is present, overlay configuration is present) for '1207662473'.
2023-06-18 16:38:46.323 [Information][SubSystem installer thread (4)] [TID 20888][galaxy_client]: Setting product event RecentlyChecked for product '1436454557' for 00min.
2023-06-18 16:38:46.828 [Information][SubSystem installer thread (4)] [TID 20888][galaxy_client]: There is not any authorisation values for '1436454557' in the database.
2023-06-18 16:38:46.828 [Warning][SubSystem installer thread (4)] [TID 20888][galaxy_client]: Failed to retrieve product auth info for '1436454557' while checking for updates.
2023-06-18 16:38:47.031 [Information][SubSystem installer thread (4)] [TID 20888][galaxy_client]: Setting product event RecentlyChecked for product '1584866499' for 00min.
2023-06-18 16:38:47.340 [Information][SubSystem installer thread (4)] [TID 20888][galaxy_client]: Retrieved valid product authorisation for '1584866499' from the database.
2023-06-18 16:38:47.340 [Information][SubSystem installer thread (4)] [TID 20888][galaxy_client]: Fetching product configuration for '1584866499'.
2023-06-18 16:38:47.456 [Error][ (0)] [TID 6140][galaxy_client]: Plugin - pluginID/steam_ca27391f-2675-49b1-92c0-896d43afa4f8 is not responding.
2023-06-18 16:38:47.456 [Information][ (0)] [TID 6140][galaxy_client]: Request to stop plugin pluginID/steam_ca27391f-2675-49b1-92c0-896d43afa4f8
2023-06-18 16:38:47.456 [Warning][ (0)] [TID 6140][galaxy_client]: Failed to import owned games from platform 'steam', reason 'Aborted'.
2023-06-18 16:38:47.456 [Information][ (0)] [TID 6140][galaxy_client]: Discarding problem report because 5s elapsed since last sending of External-Platform-Operation-Fails problem.
2023-06-18 16:38:47.459 [Information][ (0)] [TID 6140][galaxy_client]: Scheduling problem report external_platform_operation_failed (type external_integrations_failed).
2023-06-18 16:38:47.459 [Information][ (0)] [TID 6140][galaxy_client]: Discarding the problem report, 'external_platform_operation_failed (type external_integrations_failed)', because 5s has elapsed since sending the last report.
2023-06-18 16:38:47.459 [Warning][ (0)] [TID 6140][galaxy_client]: Failed to import friends from platform 'steam', reason aborted`

**Comment by don-de-marco** [comment]
Ah, frick. There's a typo in there. If you're willing to monkey patch the files, please replace `packagie_id` with `package_id` in `protobuf_client.py`.

I'll push a proper fix tomorrow

**Comment by engiefox** [comment]
No longer crashes, but nothing is syncing. The steam folder is empty and no games show on recent.
Shows this in the logs:
`2023-06-18 17:00:34,429 - steam_network.websocket_client - ERROR - Failed to establish authenticated WebSocket connection TypeError("'CMsgClientPICSProductInfoRequestPackageInfo' object cannot be interpreted as an integer")
2023-06-18 17:00:34,432 - steam_network.websocket_client - ERROR - Traceback (most recent call last):
  File "C:\Users\obliv\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\steam_network\websocket_client.py", line 111, in run
    await run_task
  File "C:\Users\obliv\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\steam_network\protocol_client.py", line 113, in run
    await self._protobuf_client.run()
  File "C:\Users\obliv\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\steam_network\protocol\protobuf_client.py", line 178, in run
    await self._process_packet(packet)
  File "C:\Users\obliv\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\steam_network\protocol\protobuf_client.py", line 518, in _process_packet
    await self._process_message(emsg, header, packet[8 + header_len:])
  File "C:\Users\obliv\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\steam_network\protocol\protobuf_client.py", line 525, in _process_message
    await self._process_multi(body)
  File "C:\Users\obliv\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\steam_network\protocol\protobuf_client.py", line 565, in _process_multi
    await self._process_packet(data[offset + size_bytes:offset + size_bytes + size])
  File "C:\Users\obliv\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\steam_network\protocol\protobuf_client.py", line 518, in _process_packet
    await self._process_message(emsg, header, packet[8 + header_len:])
  File "C:\Users\obliv\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\steam_network\protocol\protobuf_client.py", line 535, in _process_message
    await self._process_license_list(body)
  File "C:\Users\obliv\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\steam_network\protocol\protobuf_client.py", line 672, in _process_license_list
    await self.license_import_handler(licensed_apps)
  File "C:\Users\obliv\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\steam_network\protocol_client.py", line 368, in _license_import_handler
    await self._protobuf_client.get_packages_info(packages_to_import)
  File "C:\Users\obliv\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\steam_network\protocol\protobuf_client.py", line 440, in get_packages_info
    await self._send(EMsg.ClientPICSProductInfoRequest, message)
  File "C:\Users\obliv\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\steam_network\protocol\protobuf_client.py", line 482, in _send
    body = bytes(message)
  File "C:\Users\obliv\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\betterproto\__init__.py", line 629, in __bytes__
    wraps=meta.wraps or "",
  File "C:\Users\obliv\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\betterproto\__init__.py", line 360, in _serialize_single
    value = _preprocess_single(proto_type, wraps, value)
  File "C:\Users\obliv\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\betterproto\__init__.py", line 346, in _preprocess_single
    return bytes(value)
TypeError: 'CMsgClientPICSProductInfoRequestPackageInfo' object cannot be interpreted as an integer`

**Comment by don-de-marco** [comment]
Oof. That's something I cannot fix from my phone. Apparently rebasing to the upstream version of this branch broke more than I anticipated. I'll get a fix out when I'm back from work tomorrow.

**Comment by Autistic-Unicorn** [comment]
It instantly started to import games into GOG Galaxy, now lets see if it gonna import them all and all other stuff

**Comment by don-de-marco** [comment]
That's "fine". Galaxy tries to import achievements while we're still importing the games list. The errors is just us telling Galaxy to wait until the import is done; eventually, these error messages should stop and achievement import continues/starts as normal

**Comment by ABaumher** [comment]
Lmk how it goes and I'll look to merge it in if successful.

**Comment by don-de-marco** [comment]
I implemented a very aggressive caching mechanism: for all packages we only update those apps which we do not already have in our cache. That's where the line `2023-06-19 19:04:07,897 - steam_network.caches.games_cache - DEBUG - 0 apps need to be imported: set()` comes from -- all the apps referenced by the packages are already known. However, I'd recommend to reset your `steam_xxx.db` file so that you get a clean start (you could also change the value of _VERSION in game_cache.py to a different value to achieve the same). I suspect that you got an incomplete cache because of the bugs we had before.

**Comment by engiefox** [comment]
@don-de-marco just ran with your new build, seems to run just fine. synced games from an existing cache and everything. about to run without a cache, one moment

**Comment by engiefox** [comment]
it hardly spent any time at all syncing with games already in the cache, definitely a lot nicer than waiting for it to finish on every startup.

**Comment by Autistic-Unicorn** [comment]
i deleted the .db file from C:\ProgramData\GOG.com\Galaxy\storage\plugins but the games are still listed in the app. What the heck?

**Comment by engiefox** [comment]
That happens if you don't use "Disconnect" for Steam first sometimes.

**Comment by don-de-marco** [comment]
> i deleted the .db file from C:\ProgramData\GOG.com\Galaxy\storage\plugins but the games are still listed in the app. What the heck?

That's expected. Galaxy keeps an internal list of all games we imported so that it can show you your games without the actual plugin being up and running. If you want to get rid of that, click disconnect in the plugin menu and Galaxy will reset that information, too

**Comment by ABaumher** [comment]
I think this build might still have the no 2FA bug. I expressly recall testing that when first getting it working because i was sick of giving steam an email code. If the fix works on the bugfix branch i can merge them both into the dev branch. If the no 2fa bugfix works I'll have to bump the release to 1.0.7 so we'll need to make sure all our alpha builds are at least 1.1

**Comment by engiefox** [comment]
Running without cache also works for games at least. Achieves and playtime aren't syncing, but I'm giving it a moment.

**Comment by don-de-marco** [comment]
(technical side note incoming)
There's two databases in Galaxy: the one Galaxy itself uses and the one Galaxy provides for plugins to save data. So if you want to reset what Galaxy knows about the games coming from a given plugin, you need to disconnect the plugin so that Galaxy removes the information from it's own database. However, this _does not_ remove or clear the information saved to the `steam_xxx.db` file - if you reconnect the plugin afterwards, our very own caches are still intact.

Now that I'm thinking of it, I might have caused an inconvenience with my current implementation. I should probably remove the `_sent_to_galaxy` flag from the cache. This makes the plugin re-import all games into Galaxy whenever the plugin starts but at least removes the stress on steam's end since we just pass on the information we already have in our cache

**Comment by Autistic-Unicorn** [comment]
Not sure why but it got timed out again. I tried logging in twice and same thing happens.
```
...
2023-06-19 19:38:54.065 [Information][ (0)] [TID 15860][galaxy_client]: Changed the bandwidth limit in the 'Game Download' processor to <NULL>.
2023-06-19 19:38:55.536 [Warning][ (0)] [TID 14984][galaxy_client]: Failed to import owned games from platform 'steam', reason 'Timeout'.
2023-06-19 19:38:55.537 [Information][ (0)] [TID 14984][galaxy_client]: Not sending problem report as the user has disabled it.
2023-06-19 19:38:55.542 [Information][ (0)] [TID 14984][galaxy_client]: Scheduling problem report external_platform_operation_failed (type external_integrations_failed).
2023-06-19 19:38:55.542 [Information][ (0)] [TID 14984][galaxy_client]: Not sending the problem report as the user has disabled sending reports.
...
```
```
...
2023-06-19 19:37:22,847 - steam_network.caches.games_cache - DEBUG - updating app 1761270 (Half-Life: MMod); parent: None
2023-06-19 19:37:22,847 - steam_network.caches.games_cache - DEBUG - updating app 2334710 (I was born poor); parent: None
2023-06-19 19:37:22,847 - steam_network.caches.games_cache - DEBUG - updating app 1916920 (The Doll Beneath); parent: None
2023-06-19 19:37:22,847 - steam_network.caches.games_cache - DEBUG - updating app 1843190 (Brain Bait); parent: None
2023-06-19 19:37:22,847 - steam_network.caches.games_cache - DEBUG - updating app 1703930 (Kriegsfront Battlescaper); parent: None
2023-06-19 19:37:22,847 - steam_network.caches.games_cache - DEBUG - updating app 2424830 (篮球经理模拟器); parent: None
2023-06-19 19:37:22,847 - steam_network.caches.games_cache - DEBUG - import queue status -- packages: 0 | apps: 0
2023-06-19 19:37:22,847 - steam_network.caches.games_cache - INFO - Setting state to ready
2023-06-19 19:37:22,847 - steam_network.protocol.protobuf_client - DEBUG - handling 0 packages
2023-06-19 19:37:22,848 - steam_network.caches.games_cache - DEBUG - importing 0 packages
2023-06-19 19:37:22,848 - steam_network.caches.games_cache - DEBUG - 0 apps need to be imported: set()
2023-06-19 19:37:22,848 - steam_network.caches.games_cache - DEBUG - import queue status -- packages: 0 | apps: 0
2023-06-19 19:37:22,848 - steam_network.protocol.protobuf_client - DEBUG - Finished processing message Multi
...
```

**Comment by Autistic-Unicorn** [comment]
when im gonna get some time im gonna get rid of all gog galaxy files and im gonna do a completely clean install. Maybe there is some issue on my side.

**Comment by don-de-marco** [comment]
I don't think the issue is on your end. Can you try the commit I just pushed? Maybe it's related to the aggressive caching I introduced

**Comment by Autistic-Unicorn** [comment]
After 3min it failed the import due to timeout. Happens every time i restart the gog. It looks like the plugin sees the games but none of them get imported into gog.
```
2023-06-19 21:10:10.855 [Warning][ (0)] [TID 14908][galaxy_client]: Failed to import owned games from platform 'steam', reason 'Timeout'.
2023-06-19 21:10:10.855 [Information][ (0)] [TID 14908][galaxy_client]: Did not find a value under the preference key 'previewBuildsEnabled' while reading.
2023-06-19 21:10:10.870 [Information][ (0)] [TID 14908][galaxy_client]: Scheduling problem report 'External-Platform-Operation-Fails': {"Arguments":{"applicationType":"GOG Galaxy","clientVersion":"2.0.67.2","detectedOsVersion":"win10","isRunningOnWine":false,"operation":"Owned games import - 2","os":"windows","osIdentification":"windows: Windows 10 10.0 (Build 19045)","platform":"steam","updateChannel":"master"},"ProblemReport":"External-Platform-Operation-Fails"}
2023-06-19 21:10:10.873 [Information][ (0)] [TID 14908][galaxy_client]: Scheduling problem report external_platform_operation_failed (type external_integrations_failed).
2023-06-19 21:10:10.883 [Information][ (0)] [TID 17040][galaxy_client]: Sending problem report of type External-Platform-Operation-Fails: {"Arguments":{"applicationType":"GOG Galaxy","clientVersion":"2.0.67.2","detectedOsVersion":"win10","isRunningOnWine":false,"operation":"Owned games import - 2","os":"windows","osIdentification":"windows: Windows 10 10.0 (Build 19045)","platform":"steam","updateChannel":"master"},"ProblemReport":"External-Platform-Operation-Fails"}
2023-06-19 21:10:11.075 [Information][ (0)] [TID 17308][galaxy_client]: Successfully sent problem report 'external_platform_operation_failed (type external_integrations_failed)'.
2023-06-19 21:10:11.106 [Information][ (0)] [TID 17040][galaxy_client]: The problem report was successfully sent.
```

**Comment by ABaumher** [comment]
@don-de-marco you may want to squash merge in the changes i had to make to the login process to fix the broken No 2FA option. I'll do a PR on this branch for you. That said, i'm merging it into better proto deps, so maybe it'll just throw up a conflict and i can fix it in merge.

**Comment by don-de-marco** [comment]
alrighty, while I was on it and since @engiefox kept reminding me about that nastily slow achievement import, I gave StatsCache a long-deserved touch-up as well. Everyone, please be so kind and give it a try. I want to see all the bugs dug out :'D 

However, I don't think we can do much about the achievement imports for as long as we have that weird job_queue thing hanging around. From what I feel, that is where the import bottleneck is atm because it basically throttles the whole job down to 2 jobs being handled in parallel (that includes the whole send-message-and-wait-for-response round trip, btw). imo we should just send all requests off and asynchronically handle the responses similar to what we do with the PICSInfo message during license import

**Comment by don-de-marco** [comment]
I'm out for the night, just throws bugs etc at me. I'll work on the tomorrow

**Comment by ABaumher** [comment]
Actually tried firing them all off at once, it was monumentally slower, because it was blocking the recv calls until it finished. Now, sending one at a time and waiting for the recv properly might work, but i don't think the original dev know what run in executor was (the threaded version since this is io based)

**Comment by engiefox** [comment]
Only synced 6 achievements with the new build.
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log](https://github.com/ABaumher/galaxy-integration-steam/files/11794143/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)

**Comment by Autistic-Unicorn** [comment]
i have completely deleted gog and installed it again with only steam plugin installed. I'm still getting timeout error after about 3 minutes of opening the app. Nothing gets imported. Now im really not sure what is causing that.

**Comment by engiefox** [comment]
Tested the 2nd one and it didn't help. Still just the six achievements show.

**Comment by don-de-marco** [comment]
alrighty, one final set of changes. @engiefox @Autistic-Unicorn if you would be so kind and break it rq :)

**Comment by don-de-marco** [comment]
Hopefully exactly this :'D Do Achievements sync fine still?

**Comment by engiefox** [comment]
Yes, still the longest task, but it's tolerable. About 5 minutes from completing login to fully synced.

**Comment by engiefox** [comment]
Game import is probably the most impressive, less than 2 minutes to sync +800 games.

**Comment by don-de-marco** [comment]
Thanks. That one gave me the most headaches too :D 

If @Autistic-Unicorn doesn't dig out some bugs during the afternoon, I'll declare this completed @ABaumher

**Comment by Autistic-Unicorn** [comment]
Probably won't gonna do anything more since im stuck with the same error over and over again. Did create an issue at https://github.com/ABaumher/galaxy-integration-steam/issues/33 but probably i should made it at your profile instead of [ABaumher](https://github.com/ABaumher) Sorry 😞

**Comment by engiefox** [comment]
Crash after running the plugin for a few hours, crash show on the client log ~line 658 13:31:26
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log](https://github.com/ABaumher/galaxy-integration-steam/files/11808080/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)
[GalaxyClient.log](https://github.com/ABaumher/galaxy-integration-steam/files/11808082/GalaxyClient.log)

**Comment by ABaumher** [comment]
I'm hoping the bug engiefox found is just emblematic of our code still needing cleanup overall and not a bug in your code but i'll hold off until you give it a look. 

I also merged versions 1.0.6 and 1.0.7 into better proto deps (as well as the batch file fix, which i'mo not pushing to Nebula because it'll break the approvals and i don't feel like redoing them. I don't believe there will be any errors as a result of this (no conflicts != no errors at runtime, ofc), but i may be wrong. 
I know for a fact that `protobuf_client` is conflicting now (as noted by the PR) but i'm not aware how bad of a conflict this is. Sorry for adding something to your workload, lol.

**Comment by don-de-marco** [comment]
@engiefox honestly, I think you just have too many games installed. From your log I can see that Galaxy wants to import ~800 games. After exactly 20 seconds (and about 650 games done), Galaxy cuts us off because it took too long. I don't see any opportunities on how to improve our code, it's pretty straight-forward already. 
There's one single thing we could maybe change (but I'm not in favor of that idea): currently, we parse the state file of each game and check whether it's currently being downloaded (and then return the in-flight file size of what's currently already there). Instead, we could take the library information file and always return the SizeOnDisk element regardless of the being maybe being currently downloaded. That's the only thing I see that would net us some time. But as I said, I don't really like that idea and would rather have Gog just increase the import timeout to 30s or even 60s.

**Comment by don-de-marco** [comment]
@ABaumher I rebased this branch onto your current `better_protobuf_deps`. I don't see anything obvious going wrong so I guess we have a clean state rn

**Comment by ABaumher** [comment]
Ngl this is basically your branch now. I've unfortunately been dealing with more maintenance that writing any code - and a full-time job that's actually full time now (i miss the time before this project when i was on-call lol)

I'll get back to teardown when i can. 


As for the games installed issue - afaik we can update this in `tick`. Can we just timeout our code after like 18 seconds and return what we have so the plugin doesn't get sent a shutdown? If we can cache these we can fill out the rest in subsequent calls

**Comment by don-de-marco** [comment]
The game size import is handled by the plugin, not us. We just provide a means on how to get the game size for a given game id. The rest is out of our hands.

**Comment by don-de-marco** [comment]
The timeout comes from Galaxy btw, it's not triggered within our plugin. So as long as we're not able to tell Galaxy that we need more time importing the game sizes, there's nothing I know of that we can do about that

**Comment by don-de-marco** [comment]
Feel free to merge this btw. I have no changes pending

**Comment by ABaumher** [comment]
```
    async def prepare_local_size_context(self, game_ids: List[str]) -> Dict[str, str]:
        library_folders = get_library_folders()
        app_manifests = list(get_app_manifests(library_folders))
        return {app_id_from_manifest_path(path): path for path in app_manifests}
```
Is fully synchronous. running in executor makes it async and the code wouldn't be blocking

**Comment by don-de-marco** [comment]
This code just collects some file paths and is done quickly. The most work is done in `get_game_size` below that where for each game, the corresponding state file (these .vcf files in your steamapps folders) is parsed and the size returned. There's no heavy lifting going on and the GIL only is of concern when there's lots of processing, which we do not have here either. IMO it's just the I/O that's hitting us hard because we need to read a couple of hundreds of files. And that just takes time, using executors would make it even worse because of the overhead introduced by using them

**Comment by ABaumher** [comment]
we're doing a bunch of file opens.
`return vdf.load(open(path, encoding="utf-8", errors="replace"), mapper=CaseInsensitiveDict)`

Those files are never closed. That seems like it could be causing issues

**Comment by don-de-marco** [comment]
While I agree that not closing these files is bad style, it doesn't do us any harm because open files only consume a bit of memory but no CPU power

**Pull request merged**
